defaults:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  vhost: /

development:
  queue: workble_development
  exchange_type: fanout
  num_workers: 5
  persist: false
  
test: 
  queue: workble_test
  exchange_type: fanout
  num_workers: 1
  persist: false

production:
  queue: workble_production
  exchange_type: direct
  num_workers: 10
  persist: true
